"""Initial migration

Revision ID: 84c5c34084cc
Revises:
Create Date: 2024-12-22 20:49:45.153742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84c5c34084cc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('limit', sa.Integer(), nullable=True))
    op.alter_column('transaction', 'amount',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.DECIMAL(precision=8, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'amount',
               existing_type=sa.DECIMAL(precision=8, scale=2),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    op.drop_column('category', 'limit')
    # ### end Alembic commands ###
